---
- name: Installation de LibreOffice
  hosts: all
  become: true

  tasks:

    - name: Installer LibreOffice
      apt:
        name:
          - libreoffice
          - libreoffice-l10n-fr
          - libreoffice-help-fr
        state: present
        update_cache: yes
