---
- name: Configuration des postes OS elementaire
  hosts: all
  become: yes

  tasks:
    - name: Mise a jour des depots
      apt:
        update_cache: yes

    - name: Installation du client FreeIPA
      apt:
        name: freeipa-client
        state: present

    - name: Jonction au domaine FreeIPA
      command: >
        ipa-client-install --unattended --mkhomedir
        --server={{ ipa_server_url }}
        --domain={{ ipa_domain }}
        --realm={{ ipa_realm }}
        --principal={{ ipa_admin_user }}
        --password={{ ipa_admin_password }}
      args:
        creates: /etc/ipa/default.conf

    - name: Activer la saisie manuelle du login
      copy:
        dest: /etc/lightdm/lightdm.conf.d/90-manual-login.conf
        content: |
          [Seat:*]
          greeter-show-manual-login=true
        mode: '0644'

    - name: Redemarrer le service graphique
      service:
        name: lightdm
        state: restarted

    - name: Créer l'autostart ouverture Nextcloud au premier login
      copy:
        dest: /etc/X11/Xsession.d/98-nextcloud-firstlogin
        owner: root
        group: root
        mode: "0755"
        content: |
          #!/bin/bash
          FLAG="$HOME/.config/.nextcloud_opened"
          if [ ! -f "$FLAG" ]; then
            touch "$FLAG"
            sleep 5
            xdg-open "https://nextcloud.test.gca-formation.fr" &
          fi
