---
- name: Provisionnement utilisateur IPA
  hosts: localhost
  become: no
  gather_facts: no

  tasks:

    - name: Obtenir un ticket Kerberos et corriger l'expiration
      shell: |
        echo "{{ ipa_admin_password }}" | kinit admin@TEST.GCA-FORMATION.FR
        ipa user-mod {{ ipa_username }} --password-expiration="20270101000000Z"
        kdestroy
      no_log: true

    - name: Synchroniser Authentik via API
      uri:
        url: "https://authentik.test.gca-formation.fr/api/v3/sources/ldap/freeipa/sync/"
        method: RUN
        headers:
          Authorization: "Bearer {{ authentik_token }}"
          Content-Type: "application/json"
        status_code: [200, 204]
        validate_certs: no
