---
- name: Provisionnement utilisateur IPA
  hosts: localhost
  become: no
  gather_facts: no

  tasks:

    - name: Corriger l expiration du mot de passe
      shell: |
        echo "{{ ipa_admin_password }}" | kinit admin@TEST.GCA-FORMATION.FR
        ipa user-mod {{ ipa_username }} --password-expiration="20270101000000Z"
        kdestroy
      no_log: true
